const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('../swagger.json');
// ...existing code...
app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
// ...existing code...
